### ISSUE TITLE
Crash when copying from QPlainTextEdit widgets

### ISSUE THREAD

**Issue by NumerousHats** [Ukrainian-History/autoBWF#26]
Copying text from the XMP Description field using "cmd-C" or from the right-click context menu on Ubuntu 18.04  causes the following:

`Traceback (most recent call last):
  File "/home/uhec/.local/pipx/venvs/autoBWF/lib/python3.6/site-packages/autoBWF/autoBWF.py", line 484, in <lambda>
    widget.textChanged.connect(lambda element=field: self.text_changed(element))
  File "/home/uhec/.local/pipx/venvs/autoBWF/lib/python3.6/site-packages/autoBWF/autoBWF.py", line 244, in text_changed
    del self.edited_md[input_widget]
KeyError: 'xmp_description'
Aborted (core dumped)
`

**Comment by NumerousHats** [comment]
This seems to happen with any QPlainTextEdit box (not just Description), but not with QLineEdit boxes.

**Comment by NumerousHats** [comment]
Under some circumstances, a copy event in the window manager (i.e. "ctrl-C") on a QPlainTextEdit widget causes a currentTextChanged signal even if the text was not actually changed. Fixed in https://github.com/Ukrainian-History/autoBWF/commit/f2776c22fabba15aa542cf49d68f22b9bae008af
