### ISSUE TITLE
Inelegant crash if file name provided as an argument doesn't exist

### ISSUE THREAD

**Issue by NumerousHats** [Ukrainian-History/autoBWF#29]
$ autoBWF uheca_2017-21_RL2_01_prod_20170731.wav 
2022-01-25 18:56:26 uheca_2017-21_RL2_01_prod_20170731.wav: File does not exist

Traceback (most recent call last):
  File "/home/andrec/.local/bin/autoBWF", line 33, in <module>
    sys.exit(load_entry_point('autoBWF', 'console_scripts', 'autoBWF')())
  File "/home/andrec/Documents/autoBWF/autoBWF/autoBWF.py", line 816, in main
    form = MainWindow(filename, config, template)
  File "/home/andrec/Documents/autoBWF/autoBWF/autoBWF.py", line 187, in __init__
    self.original_md = self.load_file(filename)
  File "/home/andrec/Documents/autoBWF/autoBWF/autoBWF.py", line 212, in load_file
    md = bwfio.check_wave(file)
  File "/home/andrec/Documents/autoBWF/autoBWF/BWFfileIO.py", line 196, in check_wave
    md = get_bwf_tech(filename)
  File "/home/andrec/Documents/autoBWF/autoBWF/BWFfileIO.py", line 224, in get_bwf_tech
    tech_csv = subprocess.check_output(command, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwfmetaedit', '--specialchars', '--accept-nopadding', '--out-tech', 'uheca_2017-21_RL2_01_prod_20170731.wav']' returned non-zero exit status 1.

**Comment by NumerousHats** [comment]
fixed in e97906d
